# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Bump tag version & release

on:
  push:
    branches:
      - main

jobs:
  bump-tag:
    name: Bump tag version & release 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: bumptag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bumptag.outputs.tag }}
          release_name: Release ${{ steps.bumptag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: dmtmov/workflow-researcher-2
          event-type: call-deploy
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "my-key": "dima"}'
