name: deploy

on:
  release:
    types: [created]
#   create:
#     tags:
#       - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to ECR
        run: |
            echo Publishing..
            sleep 5
            echo Published!
