name: Push container

# on:
#   release:
#     types: [created]
on:
  push:
    tags:
    - '*'

jobs:
  pushContainer:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to ECR
        run: |
            echo Publishing..
            sleep 5
            echo Published!
